### ISSUE TITLE
(質問) Paddingが適応されない

### ISSUE THREAD

**Issue by K-Yuki1019** [camp-team/twitter-project#17]
## Todo

- [x] マークアップ

##  参考画像
- bosyuのページ
![image](https://user-images.githubusercontent.com/63516648/93871434-9e43d500-fd09-11ea-9122-f5a3fff408b4.png)

- 今回のページ
![image](https://user-images.githubusercontent.com/63516648/93871461-a69c1000-fd09-11ea-9f3f-7380676ef664.png)

## 何をやったか&何がしたいか

Bosyuのカード部分のPaddingが上下32pxで左右16pxだったため、Containerで全体を囲ってPaddingをかけたのですが
invalid property valueとエラーになってしまいます。
Style.scssにもContainerがあったため
```HTML
<div class="container about-container">...</div>
```
とし、Style.scssのcontainerより優先度をあげて見ましたが適応されませんでした。
初歩的な質問で申し訳ありませんがご意見頂けますと幸いです…！

## 現在のコード
- about.component.html
https://github.com/camp-team/twitter-project/blob/feature/11/src/app/welcome/about/about.component.html#L2-L39

- about.component.scss
https://github.com/camp-team/twitter-project/blob/feature/11/src/app/welcome/about/about.component.scss#L18-L31

- Style.css
https://github.com/camp-team/twitter-project/blob/feature/11/src/styles.scss#L20-L28

**Comment by mihye1128** [comment]
下記の箇所にカンマが入っちゃってます！
https://github.com/camp-team/twitter-project/blob/feature/11/src/app/welcome/about/about.component.scss##L21

```scss
// 修正後
.about-card {
  padding: 32px 16px;
}
```

**Comment by mihye1128** [comment]
ついでに、grid使ってるところの要素間の余白、下記で対応すると尚良いですね！
margin-leftを全てにかけると、左端に余計な余白ができるので
```scss
.about {
  &__grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 16px; // 追加
  }
}
.about-card {
  margin-left: 16px; // ← これを削除
}
```
